export const CARELINX_NEWS_UPDATED_AT = '2026-09-18T08:00:00.000Z'

export const CARELINX_NEWS = [
  {
    date: '2026-09-08',
    type: 'CareLinx',
    region: 'USA',
    source: 'Sharecare',
    title: 'CareLinx by Sharecare: Making the journey home possible',
    url: 'https://about.sharecare.com/carelinx-by-sharecare-making-the-journey-home-possible/',
  },
  {
    date: '2026-09-18',
    type: 'Travel Alert',
    region: 'San Francisco, CA',
    source: 'Caltrans',
    title: 'US-101 Hospital Curve: all northbound lanes and one southbound lane closed Sept. 18-21',
    url: 'https://dot.ca.gov/caltrans-near-me/district-4/d4-news/2026-09-16-us101-bayshore-freeway-full-closure',
  },
  {
    date: '2026-09-18',
    type: 'Travel Alert',
    region: 'Puget Sound, WA',
    source: 'WSDOT',
    title: 'Puget Sound highway work expected to cause congestion on I-405, I-5, and SR 520 Sept. 18-21',
    url: 'https://wsdot.wa.gov/about/news/2026/plan-ahead-busy-weekend-highway-construction-around-puget-sound-region-sept-18-21',
  },
  {
    date: '2026-09-17',
    type: 'Travel Alert',
    region: 'Truckee / I-80, CA',
    source: 'San Francisco Chronicle',
    title: 'Floriston Fire forces I-80 closure from Nevada into California near Truckee',
    url: 'https://www.sfchronicle.com/california-wildfires/article/floriston-fire-shuts-down-i-80-22435176.php',
  },
  {
    date: '2026-09-17',
    type: 'Travel Alert',
    region: 'Lake & Mendocino, CA',
    source: 'San Francisco Chronicle',
    title: 'Lucas Fire leaves evacuation zones and road controls in Northern California',
    url: 'https://www.sfchronicle.com/california-wildfires/article/lucas-fire-cause-22435521.php',
  },
  {
    date: '2026-09-16',
    type: 'Travel Alert',
    region: 'San Francisco, CA',
    source: 'San Francisco Chronicle',
    title: 'Dreamforce road closures and downtown congestion continue around Moscone Center through Sept. 20',
    url: 'https://www.sfchronicle.com/sf/article/dreamforce-street-closures-traffic-22433162.php',
  },
  {
    date: '2026-09-14',
    type: 'Travel Alert',
    region: 'Orange County, CA',
    source: 'The Guardian',
    title: 'Hurricane Marie swell causes coastal flooding, erosion, and property damage in Orange County',
    url: 'https://www.theguardian.com/environment/2026/sep/14/weather-tracker-floods-eastern-india-and-hurricane-damage-california',
  },
  {
    date: '2026-09-18',
    type: 'Caregiver Law',
    region: 'Washington',
    source: 'WA Department of Health',
    title: 'Home care aides can work up to 365 days while completing credentialing under temporary Washington rules',
    url: 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/home-care-aide',
  },
  {
    date: '2026-09-18',
    type: 'Caregiver Law',
    region: 'Washington',
    source: 'WA Cares Fund',
    title: 'WA Cares benefits now allow approved family caregivers to be paid through registered providers',
    url: 'https://wacaresfund.wa.gov/paid-family-caregiver',
  },
  {
    date: '2026-09-02',
    type: 'Caregiver Law',
    region: 'Washington',
    source: 'Working Washington',
    title: 'Washington Supreme Court ruling strengthens minimum-wage and workplace protections for live-in care workers',
    url: 'https://workingwa.org/2026/07/2026-7-10-pmzi1w8qfokzdk9vhh8pcvwp5erhoj/',
  },
  {
    date: '2026-07-01',
    type: 'Caregiver Law',
    region: 'Washington',
    source: 'WA Legislature',
    title: 'Updated home care aide certification exemptions take effect, including expanded spouse/domestic-partner exemptions',
    url: 'https://app.leg.wa.gov/wac/default.aspx?cite=246-980-025',
  },
  {
    date: '2026-09-18',
    type: 'Caregiver Law',
    region: 'California',
    source: 'CA DIR',
    title: 'California reminder: receiving a 1099 does not by itself make a caregiver an independent contractor; worker classification uses legal tests',
    url: 'https://www.dir.ca.gov/dlse/faq_independentcontractor.htm',
  },
  {
    date: '2026-09-18',
    type: 'Caregiver Law',
    region: 'Washington',
    source: 'WA Legislature',
    title: 'Washington domestic-worker law includes home care workers and independent contractors, with specified exemptions',
    url: 'https://app6.leg.wa.gov/rcw/default.aspx?cite=49.96.010',
  },
]
