export const HEALTHCARE_NEWS_UPDATED_AT = '2026-09-17T11:30:00.000Z'

export const HEALTHCARE_NEWS = [
  {
    date: '2026-09-17',
    region: 'USA',
    source: 'CMS',
    title: 'MLN Connects: ACCESS Model, Rural Health, and IRF Final Rule Webinar',
    url: 'https://www.cms.gov/training-education/medicare-learning-network/newsletter',
  },
  {
    date: '2026-09-15',
    region: 'USA',
    source: 'CMS',
    title: 'CMS Adds Medicare Options for Heart Failure, COPD, Substance Use Disorder, and Other Chronic Conditions',
    url: 'https://www.cms.gov/newsroom/press-releases/cms-adds-medicare-options-help-people-manage-substance-use-disorder-heart-failure-other-common',
  },
  {
    date: '2026-09-15',
    region: 'USA',
    source: 'CMS',
    title: '$104 Million Announced for Rural Healthcare Technology and Expanded Care in Mississippi',
    url: 'https://www.cms.gov/newsroom/press-releases/trump-administration-announces-104-million-transform-rural-healthcare-across-mississippi-through',
  },
  {
    date: '2026-09-14',
    region: 'USA',
    source: 'CMS',
    title: 'Preventive, Acute, and Behavioral Healthcare Access Expands for Rural North Carolina Students',
    url: 'https://www.cms.gov/newsroom/press-releases/trump-administration-expands-preventive-behavioral-healthcare-access-students-across-rural-north',
  },
  {
    date: '2026-09-14',
    region: 'USA',
    source: 'CMS',
    title: 'Nearly $17 Million Announced for Rural Healthcare Technology and Patient Transportation in Kansas',
    url: 'https://www.cms.gov/newsroom/press-releases/trump-administration-announces-nearly-17-million-adopt-emerging-healthcare-technologies-improve',
  },
  {
    date: '2026-09-10',
    region: 'USA',
    source: 'CMS',
    title: '$11.7 Million Announced to Strengthen Rural Nursing Homes and Long-Term Care Workforce in Vermont',
    url: 'https://www.cms.gov/newsroom/press-releases/trump-administration-announces-11-7-million-expand-access-improve-patient-care-facilities-strengthen',
  },
  {
    date: '2026-09-08',
    region: 'USA',
    source: 'CMS',
    title: 'CMS Bars 11 Medical Supply Companies Tied to $3.4 Billion in Suspected Fraudulent Billing',
    url: 'https://www.cms.gov/newsroom/press-releases/cms-cracks-down-massive-3-4-billion-medical-equipment-supplier-fraud-scheme',
  },
  {
    date: '2026-09-03',
    region: 'USA',
    source: 'CMS',
    title: 'CMS Announces September Updates for Home Health PEPPER, NCCI Edits, Screening, and Medicare Guidance',
    url: 'https://www.cms.gov/training-education/medicare-learning-network/newsletter/mln-connects-newsletter-september-3-2026',
  },
  {
    date: '2026-09-15',
    region: 'California',
    source: 'CA DHCS',
    title: 'California Posts New Medi-Cal Fee-for-Service Transition Resources and September 30 Webinar',
    url: 'https://www.dhcs.ca.gov/news/stakeholder-news-september-14-2026/',
  },
  {
    date: '2026-09-15',
    region: 'California',
    source: 'CA DHCS',
    title: 'Protect Access to Health Care Act Stakeholder Advisory Committee Meeting Set for September 18',
    url: 'https://www.dhcs.ca.gov/news/stakeholder-news-september-14-2026/',
  },
  {
    date: '2026-09-11',
    region: 'California',
    source: 'CA DHCS',
    title: 'Medi-Cal Issues Outreach Guidance on Six-Month Renewals and Work and Community Engagement Rules',
    url: 'https://www.dhcs.ca.gov/services/medi-cal-resources/medi-cal-eligibility-division/all-county-welfare-directors-medi-cal-eligibility-division-information-letters/2026-medi-cal-eligibility-division-information-letters/',
  },
  {
    date: '2026-09-08',
    region: 'California',
    source: 'CA DHCS',
    title: 'Medi-Cal Publishes Member and Provider Resources for the January 2027 Fee-for-Service Transition',
    url: 'https://www.dhcs.ca.gov/news/stakeholder-news-september-8-2026/',
  },
  {
    date: '2026-09-16',
    region: 'Washington',
    source: 'WA HCA',
    title: 'Washington Explains How Apple Health Coverage Is Treated Under the New Public Charge Rule',
    url: 'https://www.hca.wa.gov/about-hca/news/announcements/most-apple-health-medicaid-coverage-will-not-count-against-you-public-charge-rule',
  },
  {
    date: '2026-09-06',
    region: 'Washington',
    source: 'WA HCA',
    title: 'Apple Health Adds More Eligible Rehabilitation Provider Types Under Updated Rules',
    url: 'https://www.hca.wa.gov/about-hca/apple-health-medicaid-rulemaking',
  },
  {
    date: '2026-09-03',
    region: 'Washington',
    source: 'WA HCA',
    title: 'Washington Publishes Updated Resources on Coming Apple Health Eligibility and Renewal Changes',
    url: 'https://www.hca.wa.gov/free-or-low-cost-health-care/what-s-changing-apple-health-medicaid',
  },
  {
    date: '2026-09-15',
    region: 'USA',
    source: 'CMS',
    title: 'Medicare HETS Infrastructure Maintenance Scheduled for September 19',
    url: 'https://www.cms.gov/data-research/cms-information-technology/hipaa-eligibility-transaction-system/mcare-notifications',
  },
]
